apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-client-secret
  namespace: rabbitmq-client-system
type: Opaque
data:
  # decode instruction: decode it at https://www.base64encode.org/
  spring-rabbitmq-host: MzUuMTkyLjEyMy4xOTg=
  spring-rabbitmq-username: UmFiYml0QDEyMw==
  spring-rabbitmq-password: UmFiYml0QDEyMw==
